# Generated by Django 5.1.1 on 2024-10-18 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_rename_payment_amount_payment_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='applied_orders',
        ),
    ]
