# Generated by Django 5.1.1 on 2024-10-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_discount_applied_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='applied_orders',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
