# Generated by Django 5.1.1 on 2024-09-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yajman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yajman_profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='pandit/profile_pic'),
        ),
    ]
