# Generated by Django 5.1.1 on 2024-09-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yajman', '0002_alter_yajman_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='yajman_profile',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='yajman_profile',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
