# Generated by Django 5.1.1 on 2024-10-17 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yajman', '0004_referralcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_orders', models.PositiveIntegerField(default=1)),
                ('applied_orders', models.PositiveIntegerField(default=0)),
                ('referral_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='yajman.referralcode')),
            ],
        ),
    ]
