# Generated by Django 5.1.1 on 2024-10-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yajman', '0005_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='referral_code',
        ),
        migrations.AddField(
            model_name='discount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
