# Generated by Django 5.1.1 on 2024-10-18 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yajman', '0006_remove_discount_referral_code_discount_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
