# Generated by Django 5.1.1 on 2024-10-18 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yajman', '0008_discount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
