# Generated by Django 5.1.1 on 2024-10-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yajman', '0009_delete_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='yajman_profile',
            name='code',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
