# Generated by Django 5.1.1 on 2024-10-18 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yajman', '0011_rename_code_yajman_profile_ref_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yajman_profile',
            name='ref_code',
        ),
    ]
