# Generated by Django 5.1.1 on 2024-10-19 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yajman', '0012_remove_yajman_profile_ref_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='yajman_profile',
            name='code',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
