# Generated by Django 5.1.1 on 2024-10-19 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yajman', '0013_yajman_profile_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yajman_profile',
            name='code',
        ),
    ]
