"""
Django settings for pandit_plus project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+v^i$+2!3a&0u###^%xnii%t7if-)%+l+!j+fuu0r%49@^eoc('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

CORS_ALLOWED_ORIGINS = ['https://*panditplus.in/','https://*www.panditplus.in/','https://www.panditplus.in/*','https://panditplus.in/*',"http://*51.20.3.130/","http://51.20.3.130/*"]
CSRF_TRUSTED_ORIGINS =  ['https://*panditplus.in/','https://*www.panditplus.in/','https://www.panditplus.in/*','https://panditplus.in/*',"http://*51.20.3.130/","http://51.20.3.130/*"]

import os


# settings.py
RAZORPAY_KEY_ID = "rzp_test_2U7cEGx2GTeRjD"
RAZORPAY_SECRET_KEY = "QSQInAxAIPndmntXueRb5Qag"




EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # or your email host like smtp.yourdomain.com
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'panditplus11@gmail.com'  # your email address
EMAIL_HOST_PASSWORD = 'kssc fyrd omav uimo'  # your email password or app-specific password for Gmail
DEFAULT_FROM_EMAIL = 'panditplus11@gmail.com'  # default sender email address

# Application definition

INSTALLED_APPS = [
    'admin_interface',
    'colorfield',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
 
    'django.contrib.staticfiles',

    'django_cleanup.apps.CleanupConfig',
    'yajman',
    'pandit',
    'payments'

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'pandit_plus.urls'
# settings.py

LOGIN_URL = '/login_as'  # Redirects to this URL when login is required


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "template")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pandit_plus.wsgi.application'


# Database


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# DATABASES = {
#         'default': {
#             'ENGINE': 'django.db.backends.mysql',
#             'NAME': 'pandit_plus',
#             'USER': 'Prabhuremote',
#             'PASSWORD': '$$Prabhu@9975$$',
#             'HOST': '51.20.3.130',  # Remote MySQL host
#             'PORT': '3306',
#         }
#     }


if DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'pandit_plus',
            'USER': 'Prabhuremote',
            'PASSWORD': '$$Prabhu@9975$$',
            'HOST': '51.20.3.130',  # Remote MySQL host
            'PORT': '3306',
        },
        'OPTIONS': {
         'connect_timeout': 60,
            }  

    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'pandit_plus',
            'USER': 'Prabhu',
            'PASSWORD': '$$Prabhu@9975$$',
            'HOST': 'localhost',  # Local MySQL host
            'PORT': '3306',
        }
    }



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'

MEDIA_URL = '/media/'

IMPORT_EXPORT_USE_TRANSACTIONS = True

if DEBUG:

  STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

else:

  STATIC_ROOT = os.path.join(BASE_DIR, 'static')

  

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
