# Generated by Django 5.1.1 on 2024-09-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pandit_profile',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pandit_profile',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
