# Generated by Django 5.1.1 on 2024-09-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandit', '0002_pandit_profile_latitude_pandit_profile_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='pandit_profile',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
