# Generated by Django 5.1.1 on 2024-10-01 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pandit', '0003_pandit_profile_is_available'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pandit_availability',
        ),
    ]
