# Generated by Django 5.1.1 on 2024-10-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandit', '0004_delete_pandit_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pandit_profile',
            name='is_available',
        ),
        migrations.AddField(
            model_name='pandit_profile',
            name='availability',
            field=models.CharField(choices=[('availabe', 'availabe'), ('busy', 'busy'), ('not_said', 'not_said')], default='not_said', max_length=50),
        ),
    ]
