# Generated by Django 5.1.1 on 2024-10-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandit', '0005_remove_pandit_profile_is_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pandit_profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='pandit/profile_pic'),
        ),
    ]
