# Generated by Django 5.1.1 on 2024-10-02 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandit', '0007_alter_pandit_service_pandit_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('conformed', 'conformed'), ('rejected', 'rejected'), ('on_hold', 'on_hold'), ('requested', 'requested')], max_length=50)),
                ('payment_status', models.CharField(choices=[('received', 'received'), ('not_received', 'not_received'), ('failed', 'failed')], default='not_received', max_length=50)),
                ('pandit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pandit_bookings', to=settings.AUTH_USER_MODEL)),
                ('yajman_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yajman_bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
