# Generated by Django 5.1.1 on 2024-10-02 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandit', '0008_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='services_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pandit.pandit_service'),
        ),
    ]
