# Generated by Django 5.1.1 on 2024-10-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandit', '0010_booking_date_booking_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='locattion',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
