# Generated by Django 5.1.1 on 2024-10-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandit', '0011_booking_locattion'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='conform_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='conform_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
