# Generated by Django 5.1.1 on 2024-10-06 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandit', '0016_booking_service_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='services_id',
            new_name='name_of_pooja',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='pandit_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='service_type',
        ),
        migrations.AddField(
            model_name='booking',
            name='name_of_pooja_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pandit.services_type'),
            preserve_default=False,
        ),
    ]
