# Generated by Django 5.1.1 on 2024-10-06 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandit', '0017_rename_services_id_booking_name_of_pooja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pandit_service',
            name='type_of_pooja',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pandit.services_type'),
            preserve_default=False,
        ),
    ]
