# Generated by Django 5.1.1 on 2024-10-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandit', '0019_booking_pandit_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pandit_profile',
            name='education',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
