# Generated by Django 5.1.1 on 2024-10-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandit', '0020_pandit_profile_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='pandit_profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
