# Generated by Django 5.1.1 on 2024-10-07 06:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandit', '0021_pandit_profile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pandit_profile',
            name='alternative_mobile',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
