# Generated by Django 5.1.1 on 2024-10-07 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pandit', '0022_pandit_profile_alternative_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pandit_profile',
            name='alternative_mobile',
        ),
    ]
