# Generated by Django 5.1.1 on 2024-10-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandit', '0023_remove_pandit_profile_alternative_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='pandit_profile',
            name='alternative_mobile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
