# Generated by Django 5.1.1 on 2024-10-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandit', '0024_pandit_profile_alternative_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='pandit_profile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
