# Generated by Django 5.1.1 on 2024-10-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandit', '0025_pandit_profile_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='pandit_profile',
            name='collage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
