# Generated by Django 5.1.1 on 2024-10-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandit', '0026_pandit_profile_collage'),
    ]

    operations = [
        migrations.AddField(
            model_name='services_type',
            name='thumbnails',
            field=models.ImageField(default='/media/default', upload_to='service_type_thumbnails'),
            preserve_default=False,
        ),
    ]
