# Generated by Django 5.1.1 on 2024-10-18 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pandit', '0027_services_type_thumbnails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='payment_status',
        ),
    ]
