# Generated by Django 5.1.1 on 2024-10-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandit', '0028_remove_booking_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('received', 'received'), ('not_received', 'not_received'), ('failed', 'failed')], default='not_received', max_length=50),
        ),
    ]
