# Generated by Django 5.1.1 on 2024-10-18 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pandit', '0029_booking_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='payment_status',
        ),
    ]
