# Generated by Django 5.1.1 on 2024-10-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandit', '0031_booking_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pandit_profile',
            name='availability',
            field=models.CharField(choices=[('online', 'online'), ('busy', 'busy'), ('not_said', 'not_said')], default='not_said', max_length=50),
        ),
    ]
