# Generated by Django 5.1.1 on 2024-10-28 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pandit', '0032_alter_pandit_profile_availability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='locattion',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='name_of_pooja_category',
        ),
    ]
