# Generated by Django 5.1.1 on 2024-10-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandit', '0033_rename_locattion_booking_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services_type',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
